//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABETModelContainer : DbContext
    {
        public ABETModelContainer()
            : base("name=ABETModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<ClassRevision> ClassRevisions { get; set; }
        public DbSet<StudentLearningObjectives> StudentLearningObjectives { get; set; }
        public DbSet<StudentLearningObjectivesRevisions> StudentLearningObjectivesRevisions { get; set; }
    }
}
