//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassRevisions = new HashSet<ClassRevision>();
        }
    
        public int ClassId { get; set; }
    
        public virtual ICollection<ClassRevision> ClassRevisions { get; set; }
        public virtual ClassRevision CurrentRevision { get; set; }
    }
}
