//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLearningObjectivesRevisions
    {
        public int RevisionId { get; set; }
        public int StudentLearningObjectivesSLOId { get; set; }
    
        public virtual StudentLearningObjectives StudentLearningObjective { get; set; }
    }
}
